stages:
- name: test1
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        java --version
        pwd
        ls
- name: test2
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: sleep 360
timeout: 60
